const { currencyNames } = require('@base/constants/enums/currency');

const Countries = [
  { value: 'AF', isoCode: '', text: 'Afghanistan' },
  { value: 'AX', isoCode: '', text: 'Åland Islands' },
  { value: 'AL', isoCode: '', text: 'Albania' },
  { value: 'DZ', isoCode: '', text: 'Algeria' },
  { value: 'AS', isoCode: '', text: 'American Samoa' },
  { value: 'AD', isoCode: '', text: 'Andorra' },
  { value: 'AO', isoCode: '', text: 'Angola' },
  { value: 'AI', isoCode: '', text: 'Anguilla' },
  { value: 'AQ', isoCode: '', text: 'Antarctica' },
  { value: 'AG', isoCode: '', text: 'Antigua and Barbuda' },
  { value: 'AR', isoCode: '', text: 'Argentina' },
  { value: 'AM', isoCode: '', text: 'Armenia' },
  { value: 'AW', isoCode: '', text: 'Aruba' },
  { value: 'AU', isoCode: currencyNames.aud, text: 'Australia' },
  { value: 'AT', isoCode: currencyNames.eur, text: 'Austria' },
  { value: 'AZ', isoCode: '', text: 'Azerbaijan' },
  { value: 'BS', isoCode: '', text: 'Bahamas' },
  { value: 'BH', isoCode: '', text: 'Bahrain' },
  { value: 'BD', isoCode: '', text: 'Bangladesh' },
  { value: 'BB', isoCode: '', text: 'Barbados' },
  { value: 'BY', isoCode: '', text: 'Belarus' },
  { value: 'BE', isoCode: currencyNames.eur, text: 'Belgium' },
  { value: 'BZ', isoCode: '', text: 'Belize' },
  { value: 'BJ', isoCode: '', text: 'Benin' },
  { value: 'BM', isoCode: '', text: 'Bermuda' },
  { value: 'BT', isoCode: '', text: 'Bhutan' },
  { value: 'BO', isoCode: '', text: 'Bolivia, Plurinational State of' },
  { value: 'BQ', isoCode: '', text: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'BA', isoCode: '', text: 'Bosnia and Herzegovina' },
  { value: 'BW', isoCode: '', text: 'Botswana' },
  { value: 'BV', isoCode: '', text: 'Bouvet Island' },
  { value: 'BR', isoCode: '', text: 'Brazil' },
  { value: 'IO', isoCode: '', text: 'British Indian Ocean Territory' },
  { value: 'BN', isoCode: '', text: 'Brunei Darussalam' },
  { value: 'BG', isoCode: '', text: 'Bulgaria' },
  { value: 'BF', isoCode: '', text: 'Burkina Faso' },
  { value: 'BI', isoCode: '', text: 'Burundi' },
  { value: 'KH', isoCode: '', text: 'Cambodia' },
  { value: 'CM', isoCode: '', text: 'Cameroon' },
  { value: 'CA', isoCode: '', text: 'Canada' },
  { value: 'CV', isoCode: '', text: 'Cape Verde' },
  { value: 'KY', isoCode: '', text: 'Cayman Islands' },
  { value: 'CF', isoCode: '', text: 'Central African Republic' },
  { value: 'TD', isoCode: '', text: 'Chad' },
  { value: 'CL', isoCode: '', text: 'Chile' },
  { value: 'CN', isoCode: '', text: 'China' },
  { value: 'CX', isoCode: '', text: 'Christmas Island' },
  { value: 'CC', isoCode: '', text: 'Cocos (Keeling) Islands' },
  { value: 'CO', isoCode: '', text: 'Colombia' },
  { value: 'KM', isoCode: '', text: 'Comoros' },
  { value: 'CG', isoCode: '', text: 'Congo' },
  { value: 'CD', isoCode: '', text: 'Congo, the Democratic Republic of the' },
  { value: 'CK', isoCode: '', text: 'Cook Islands' },
  { value: 'CR', isoCode: '', text: 'Costa Rica' },
  { value: 'CI', isoCode: '', text: "Côte d'Ivoire" },
  { value: 'HR', isoCode: '', text: 'Croatia' },
  { value: 'CU', isoCode: '', text: 'Cuba' },
  { value: 'CW', isoCode: '', text: 'Curaçao' },
  { value: 'CY', isoCode: currencyNames.eur, text: 'Cyprus' },
  { value: 'CZ', isoCode: '', text: 'Czech Republic' },
  { value: 'DK', isoCode: '', text: 'Denmark' },
  { value: 'DJ', isoCode: '', text: 'Djibouti' },
  { value: 'DM', isoCode: '', text: 'Dominica' },
  { value: 'DO', isoCode: '', text: 'Dominican Republic' },
  { value: 'EC', isoCode: '', text: 'Ecuador' },
  { value: 'EG', isoCode: '', text: 'Egypt' },
  { value: 'SV', isoCode: '', text: 'El Salvador' },
  { value: 'GQ', isoCode: '', text: 'Equatorial Guinea' },
  { value: 'ER', isoCode: '', text: 'Eritrea' },
  { value: 'EE', isoCode: currencyNames.eur, text: 'Estonia' },
  { value: 'ET', isoCode: '', text: 'Ethiopia' },
  { value: 'FK', isoCode: '', text: 'Falkland Islands (Malvinas)' },
  { value: 'FO', isoCode: '', text: 'Faroe Islands' },
  { value: 'FJ', isoCode: '', text: 'Fiji' },
  { value: 'FI', isoCode: currencyNames.eur, text: 'Finland' },
  { value: 'FR', isoCode: currencyNames.eur, text: 'France' },
  { value: 'GF', isoCode: '', text: 'French Guiana' },
  { value: 'PF', isoCode: '', text: 'French Polynesia' },
  { value: 'TF', isoCode: '', text: 'French Southern Territories' },
  { value: 'GA', isoCode: '', text: 'Gabon' },
  { value: 'GM', isoCode: '', text: 'Gambia' },
  { value: 'GE', isoCode: '', text: 'Georgia' },
  { value: 'DE', isoCode: currencyNames.eur, text: 'Germany' },
  { value: 'GH', isoCode: '', text: 'Ghana' },
  { value: 'GI', isoCode: '', text: 'Gibraltar' },
  { value: 'GR', isoCode: currencyNames.eur, text: 'Greece' },
  { value: 'GL', isoCode: '', text: 'Greenland' },
  { value: 'GD', isoCode: '', text: 'Grenada' },
  { value: 'GP', isoCode: '', text: 'Guadeloupe' },
  { value: 'GU', isoCode: '', text: 'Guam' },
  { value: 'GT', isoCode: '', text: 'Guatemala' },
  { value: 'GG', isoCode: '', text: 'Guernsey' },
  { value: 'GN', isoCode: '', text: 'Guinea' },
  { value: 'GW', isoCode: '', text: 'Guinea-Bissau' },
  { value: 'GY', isoCode: '', text: 'Guyana' },
  { value: 'HT', isoCode: '', text: 'Haiti' },
  { value: 'HM', isoCode: '', text: 'Heard Island and McDonald Islands' },
  { value: 'VA', isoCode: '', text: 'Holy See (Vatican City State)' },
  { value: 'HN', isoCode: '', text: 'Honduras' },
  { value: 'HK', isoCode: '', text: 'Hong Kong' },
  { value: 'HU', isoCode: '', text: 'Hungary' },
  { value: 'IS', isoCode: '', text: 'Iceland' },
  { value: 'IN', isoCode: '', text: 'India' },
  { value: 'ID', isoCode: '', text: 'Indonesia' },
  { value: 'IR', isoCode: '', text: 'Iran, Islamic Republic of' },
  { value: 'IQ', isoCode: '', text: 'Iraq' },
  { value: 'IE', isoCode: currencyNames.eur, text: 'Ireland' },
  { value: 'IM', isoCode: '', text: 'Isle of Man' },
  { value: 'IL', isoCode: '', text: 'Israel' },
  { value: 'IT', isoCode: currencyNames.eur, text: 'Italy' },
  { value: 'JM', isoCode: '', text: 'Jamaica' },
  { value: 'JP', isoCode: '', text: 'Japan' },
  { value: 'JE', isoCode: '', text: 'Jersey' },
  { value: 'JO', isoCode: '', text: 'Jordan' },
  { value: 'KZ', isoCode: '', text: 'Kazakhstan' },
  { value: 'KE', isoCode: '', text: 'Kenya' },
  { value: 'KI', isoCode: '', text: 'Kiribati' },
  { value: 'KP', isoCode: '', text: "Korea, Democratic People's Republic of" },
  { value: 'KR', isoCode: '', text: 'Korea, Republic of' },
  { value: 'KW', isoCode: '', text: 'Kuwait' },
  { value: 'KG', isoCode: '', text: 'Kyrgyzstan' },
  { value: 'LA', isoCode: '', text: "Lao People's Democratic Republic" },
  { value: 'LV', isoCode: currencyNames.eur, text: 'Latvia' },
  { value: 'LB', isoCode: '', text: 'Lebanon' },
  { value: 'LS', isoCode: '', text: 'Lesotho' },
  { value: 'LR', isoCode: '', text: 'Liberia' },
  { value: 'LY', isoCode: '', text: 'Libya' },
  { value: 'LI', isoCode: '', text: 'Liechtenstein' },
  { value: 'LT', isoCode: currencyNames.eur, text: 'Lithuania' },
  { value: 'LU', isoCode: currencyNames.eur, text: 'Luxembourg' },
  { value: 'MO', isoCode: '', text: 'Macao' },
  { value: 'MK', isoCode: '', text: 'Macedonia, the former Yugoslav Republic of' },
  { value: 'MG', isoCode: '', text: 'Madagascar' },
  { value: 'MW', isoCode: '', text: 'Malawi' },
  { value: 'MY', isoCode: '', text: 'Malaysia' },
  { value: 'MV', isoCode: '', text: 'Maldives' },
  { value: 'ML', isoCode: '', text: 'Mali' },
  { value: 'MT', isoCode: currencyNames.eur, text: 'Malta' },
  { value: 'MH', isoCode: '', text: 'Marshall Islands' },
  { value: 'MQ', isoCode: '', text: 'Martinique' },
  { value: 'MR', isoCode: '', text: 'Mauritania' },
  { value: 'MU', isoCode: '', text: 'Mauritius' },
  { value: 'YT', isoCode: '', text: 'Mayotte' },
  { value: 'MX', isoCode: '', text: 'Mexico' },
  { value: 'FM', isoCode: '', text: 'Micronesia, Federated States of' },
  { value: 'MD', isoCode: '', text: 'Moldova, Republic of' },
  { value: 'MC', isoCode: '', text: 'Monaco' },
  { value: 'MN', isoCode: '', text: 'Mongolia' },
  { value: 'ME', isoCode: '', text: 'Montenegro' },
  { value: 'MS', isoCode: '', text: 'Montserrat' },
  { value: 'MA', isoCode: '', text: 'Morocco' },
  { value: 'MZ', isoCode: '', text: 'Mozambique' },
  { value: 'MM', isoCode: '', text: 'Myanmar' },
  { value: 'NA', isoCode: '', text: 'Namibia' },
  { value: 'NR', isoCode: '', text: 'Nauru' },
  { value: 'NP', isoCode: '', text: 'Nepal' },
  { value: 'NL', isoCode: currencyNames.eur, text: 'Netherlands' },
  { value: 'NC', isoCode: '', text: 'New Caledonia' },
  { value: 'NZ', isoCode: currencyNames.nzd, text: 'New Zealand' },
  { value: 'NI', isoCode: '', text: 'Nicaragua' },
  { value: 'NE', isoCode: '', text: 'Niger' },
  { value: 'NG', isoCode: '', text: 'Nigeria' },
  { value: 'NU', isoCode: '', text: 'Niue' },
  { value: 'NF', isoCode: '', text: 'Norfolk Island' },
  { value: 'MP', isoCode: '', text: 'Northern Mariana Islands' },
  { value: 'NO', isoCode: '', text: 'Norway' },
  { value: 'OM', isoCode: '', text: 'Oman' },
  { value: 'PK', isoCode: '', text: 'Pakistan' },
  { value: 'PW', isoCode: '', text: 'Palau' },
  { value: 'PS', isoCode: '', text: 'Palestinian Territory, Occupied' },
  { value: 'PA', isoCode: '', text: 'Panama' },
  { value: 'PG', isoCode: '', text: 'Papua New Guinea' },
  { value: 'PY', isoCode: '', text: 'Paraguay' },
  { value: 'PE', isoCode: '', text: 'Peru' },
  { value: 'PH', isoCode: '', text: 'Philippines' },
  { value: 'PN', isoCode: '', text: 'Pitcairn' },
  { value: 'PL', isoCode: '', text: 'Poland' },
  { value: 'PT', isoCode: currencyNames.eur, text: 'Portugal' },
  { value: 'PR', isoCode: '', text: 'Puerto Rico' },
  { value: 'QA', isoCode: '', text: 'Qatar' },
  { value: 'RE', isoCode: '', text: 'Réunion' },
  { value: 'RO', isoCode: '', text: 'Romania' },
  { value: 'RU', isoCode: '', text: 'Russian Federation' },
  { value: 'RW', isoCode: '', text: 'Rwanda' },
  { value: 'BL', isoCode: '', text: 'Saint Barthélemy' },
  { value: 'SH', isoCode: '', text: 'Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'KN', isoCode: '', text: 'Saint Kitts and Nevis' },
  { value: 'LC', isoCode: '', text: 'Saint Lucia' },
  { value: 'MF', isoCode: '', text: 'Saint Martin (French part)' },
  { value: 'PM', isoCode: '', text: 'Saint Pierre and Miquelon' },
  { value: 'VC', isoCode: '', text: 'Saint Vincent and the Grenadines' },
  { value: 'WS', isoCode: '', text: 'Samoa' },
  { value: 'SM', isoCode: '', text: 'San Marino' },
  { value: 'ST', isoCode: '', text: 'Sao Tome and Principe' },
  { value: 'SA', isoCode: '', text: 'Saudi Arabia' },
  { value: 'SN', isoCode: '', text: 'Senegal' },
  { value: 'RS', isoCode: '', text: 'Serbia' },
  { value: 'SC', isoCode: '', text: 'Seychelles' },
  { value: 'SL', isoCode: '', text: 'Sierra Leone' },
  { value: 'SG', isoCode: '', text: 'Singapore' },
  { value: 'SX', isoCode: '', text: 'Sint Maarten (Dutch part)' },
  { value: 'SK', isoCode: currencyNames.eur, text: 'Slovakia' },
  { value: 'SI', isoCode: currencyNames.eur, text: 'Slovenia' },
  { value: 'SB', isoCode: '', text: 'Solomon Islands' },
  { value: 'SO', isoCode: '', text: 'Somalia' },
  { value: 'ZA', isoCode: '', text: 'South Africa' },
  { value: 'GS', isoCode: '', text: 'South Georgia and the South Sandwich Islands' },
  { value: 'SS', isoCode: '', text: 'South Sudan' },
  { value: 'ES', isoCode: currencyNames.eur, text: 'Spain' },
  { value: 'LK', isoCode: '', text: 'Sri Lanka' },
  { value: 'SD', isoCode: '', text: 'Sudan' },
  { value: 'SR', isoCode: '', text: 'Suriname' },
  { value: 'SJ', isoCode: '', text: 'Svalbard and Jan Mayen' },
  { value: 'SZ', isoCode: '', text: 'Swaziland' },
  { value: 'SE', isoCode: '', text: 'Sweden' },
  { value: 'CH', isoCode: '', text: 'Switzerland' },
  { value: 'SY', isoCode: '', text: 'Syrian Arab Republic' },
  { value: 'TW', isoCode: '', text: 'Taiwan, Province of China' },
  { value: 'TJ', isoCode: '', text: 'Tajikistan' },
  { value: 'TZ', isoCode: '', text: 'Tanzania, United Republic of' },
  { value: 'TH', isoCode: '', text: 'Thailand' },
  { value: 'TL', isoCode: '', text: 'Timor-Leste' },
  { value: 'TG', isoCode: '', text: 'Togo' },
  { value: 'TK', isoCode: '', text: 'Tokelau' },
  { value: 'TO', isoCode: '', text: 'Tonga' },
  { value: 'TT', isoCode: '', text: 'Trinidad and Tobago' },
  { value: 'TN', isoCode: '', text: 'Tunisia' },
  { value: 'TR', isoCode: '', text: 'Turkey' },
  { value: 'TM', isoCode: '', text: 'Turkmenistan' },
  { value: 'TC', isoCode: '', text: 'Turks and Caicos Islands' },
  { value: 'TV', isoCode: '', text: 'Tuvalu' },
  { value: 'UG', isoCode: '', text: 'Uganda' },
  { value: 'UA', isoCode: '', text: 'Ukraine' },
  { value: 'AE', isoCode: '', text: 'United Arab Emirates' },
  { value: 'GB', isoCode: currencyNames.gbp, text: 'United Kingdom' },
  { value: 'US', isoCode: '', text: 'United States' },
  { value: 'UM', isoCode: '', text: 'United States Minor Outlying Islands' },
  { value: 'UY', isoCode: '', text: 'Uruguay' },
  { value: 'UZ', isoCode: '', text: 'Uzbekistan' },
  { value: 'VU', isoCode: '', text: 'Vanuatu' },
  { value: 'VE', isoCode: '', text: 'Venezuela, Bolivarian Republic of' },
  { value: 'VN', isoCode: '', text: 'Viet Nam' },
  { value: 'VG', isoCode: '', text: 'Virgin Islands, British' },
  { value: 'VI', isoCode: '', text: 'Virgin Islands, U.S.' },
  { value: 'WF', isoCode: '', text: 'Wallis and Futuna' },
  { value: 'EH', isoCode: '', text: 'Western Sahara' },
  { value: 'YE', isoCode: '', text: 'Yemen' },
  { value: 'ZM', isoCode: '', text: 'Zambia' },
  { value: 'ZW', isoCode: '', text: 'Zimbabwe' },
];

module.exports = {
  Countries,
};
