const Timezones = [
  {
    text: '(GMT-12:00) International Date Line West',
    value: '(GMT-12:00) International Date Line West',
    offsetName: 'GMT-12:00',
    useDaylightTime: false,
    offset: -720,
  },
  {
    text: '(GMT-11:00) Midway Island, Samoa',
    value: '(GMT-11:00) Midway Island, Samoa',
    offsetName: 'GMT-11:00',
    useDaylightTime: false,
    offset: -660,
  },
  {
    text: '(GMT-10:00) Hawaii',
    value: '(GMT-10:00) Hawaii',
    offsetName: 'GMT-10:00',
    useDaylightTime: false,
    offset: -600,
  },
  {
    text: '(GMT-09:00) Alaska',
    value: '(GMT-09:00) Alaska',
    offsetName: 'GMT-09:00',
    useDaylightTime: true,
    offset: -540,
  },
  {
    text: '(GMT-08:00) Pacific Time (US & Canada)',
    value: '(GMT-08:00) Pacific Time (US & Canada)',
    offsetName: 'GMT-08:00',
    useDaylightTime: true,
    offset: -480,
  },
  {
    text: '(GMT-08:00) Tijuana, Baja California',
    value: '(GMT-08:00) Tijuana, Baja California',
    offsetName: 'GMT-08:00',
    useDaylightTime: true,
    offset: -480,
  },
  {
    text: '(GMT-07:00) Arizona',
    value: '(GMT-07:00) Arizona',
    offsetName: 'GMT-07:00',
    useDaylightTime: false,
    offset: -420,
  },
  {
    text: '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
    value: '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
    offsetName: 'GMT-07:00',
    useDaylightTime: true,
    offset: -420,
  },
  {
    text: '(GMT-07:00) Mountain Time (US & Canada)',
    value: '(GMT-07:00) Mountain Time (US & Canada)',
    offsetName: 'GMT-07:00',
    useDaylightTime: true,
    offset: -420,
  },
  {
    text: '(GMT-06:00) Central America',
    value: '(GMT-06:00) Central America',
    offsetName: 'GMT-06:00',
    useDaylightTime: false,
    offset: -360,
  },
  {
    text: '(GMT-06:00) Central Time (US & Canada)',
    value: '(GMT-06:00) Central Time (US & Canada)',
    offsetName: 'GMT-06:00',
    useDaylightTime: true,
    offset: -360,
  },
  {
    text: '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
    value: '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
    offsetName: 'GMT-06:00',
    useDaylightTime: true,
    offset: -360,
  },
  {
    text: '(GMT-06:00) Saskatchewan',
    value: '(GMT-06:00) Saskatchewan',
    offsetName: 'GMT-06:00',
    useDaylightTime: false,
    offset: -360,
  },
  {
    text: '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
    value: '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
    offsetName: 'GMT-05:00',
    useDaylightTime: false,
    offset: -300,
  },
  {
    text: '(GMT-05:00) Eastern Time (US & Canada)',
    value: '(GMT-05:00) Eastern Time (US & Canada)',
    offsetName: 'GMT-05:00',
    useDaylightTime: true,
    offset: -300,
  },
  {
    text: '(GMT-05:00) Indiana (East)',
    value: '(GMT-05:00) Indiana (East)',
    offsetName: 'GMT-05:00',
    useDaylightTime: true,
    offset: -300,
  },
  {
    text: '(GMT-04:00) Atlantic Time (Canada)',
    value: '(GMT-04:00) Atlantic Time (Canada)',
    offsetName: 'GMT-04:00',
    useDaylightTime: true,
    offset: -240,
  },
  {
    text: '(GMT-04:00) Caracas, La Paz',
    value: '(GMT-04:00) Caracas, La Paz',
    offsetName: 'GMT-04:00',
    useDaylightTime: false,
    offset: -240,
  },
  {
    text: '(GMT-04:00) Manaus',
    value: '(GMT-04:00) Manaus',
    offsetName: 'GMT-04:00',
    useDaylightTime: false,
    offset: -240,
  },
  {
    text: '(GMT-04:00) Santiago',
    value: '(GMT-04:00) Santiago',
    offsetName: 'GMT-04:00',
    useDaylightTime: true,
    offset: -240,
  },
  {
    text: '(GMT - 03:30) Newfoundland',
    value: '(GMT - 03:30) Newfoundland',
    offsetName: 'GMT-03:30',
    useDaylightTime: true,
    offset: -180,
  },
  {
    text: '(GMT-03:00) Brasilia',
    value: '(GMT-03:00) Brasilia',
    offsetName: 'GMT-03:00',
    useDaylightTime: true,
    offset: -180,
  },
  {
    text: '(GMT-03:00) Buenos Aires, Georgetown',
    value: '(GMT-03:00) Buenos Aires, Georgetown',
    offsetName: 'GMT-03:00',
    useDaylightTime: false,
    offset: -180,
  },
  {
    text: '(GMT-03:00) Greenland',
    value: '(GMT-03:00) Greenland',
    offsetName: 'GMT-03:00',
    useDaylightTime: true,
    offset: -180,
  },
  {
    text: '(GMT-03:00) Montevideo',
    value: '(GMT-03:00) Montevideo',
    offsetName: 'GMT-03:00',
    useDaylightTime: true,
    offset: -180,
  },
  {
    text: '(GMT-02:00) Mid-Atlantic',
    value: '(GMT-02:00) Mid-Atlantic',
    offsetName: 'GMT-02:00',
    useDaylightTime: true,
    offset: -120,
  },
  {
    text: '(GMT-01:00) Cape Verde Is.',
    value: '(GMT-01:00) Cape Verde Is.',
    offsetName: 'GMT-01:00',
    useDaylightTime: false,
    offset: -60,
  },
  {
    text: '(GMT-01:00) Azores',
    value: '(GMT-01:00) Azores',
    offsetName: 'GMT-01:00',
    useDaylightTime: true,
    offset: -60,
  },
  {
    text: '(GMT+00:00) Casablanca, Monrovia, Reykjavik',
    value: '(GMT+00:00) Casablanca, Monrovia, Reykjavik',
    offsetName: 'GMT+00:00',
    useDaylightTime: false,
    offset: 0,
  },
  {
    text: '(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',
    value: '(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',
    offsetName: 'GMT+00:00',
    useDaylightTime: true,
    offset: 0,
  },
  {
    text: '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    value: '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    offsetName: 'GMT+01:00',
    useDaylightTime: true,
    offset: 60,
  },
  {
    text: '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    value: '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    offsetName: 'GMT+01:00',
    useDaylightTime: true,
    offset: 60,
  },
  {
    text: '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
    value: '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
    offsetName: 'GMT+01:00',
    useDaylightTime: true,
    offset: 60,
  },
  {
    text: '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    value: '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    offsetName: 'GMT+01:00',
    useDaylightTime: true,
    offset: 60,
  },
  {
    text: '(GMT+01:00) West Central Africa',
    value: '(GMT+01:00) West Central Africa',
    offsetName: 'GMT+01:00',
    useDaylightTime: true,
    offset: 60,
  },
  {
    text: '(GMT+02:00) Amman',
    value: '(GMT+02:00) Amman',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Athens, Bucharest, Istanbul',
    value: '(GMT+02:00) Athens, Bucharest, Istanbul',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Beirut',
    value: '(GMT+02:00) Beirut',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Cairo',
    value: '(GMT+02:00) Cairo',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Harare, Pretoria',
    value: '(GMT+02:00) Harare, Pretoria',
    offsetName: 'GMT+02:00',
    useDaylightTime: false,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    value: '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Jerusalem',
    value: '(GMT+02:00) Jerusalem',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Minsk',
    value: '(GMT+02:00) Minsk',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+02:00) Windhoek',
    value: '(GMT+02:00) Windhoek',
    offsetName: 'GMT+02:00',
    useDaylightTime: true,
    offset: 120,
  },
  {
    text: '(GMT+03:00) Kuwait, Riyadh, Baghdad',
    value: '(GMT+03:00) Kuwait, Riyadh, Baghdad',
    offsetName: 'GMT+03:00',
    useDaylightTime: false,
    offset: 180,
  },
  {
    text: '(GMT+03:00) Moscow, St. Petersburg, Volgograd',
    value: '(GMT+03:00) Moscow, St. Petersburg, Volgograd',
    offsetName: 'GMT+03:00',
    useDaylightTime: true,
    offset: 180,
  },
  {
    text: '(GMT+03:00) Nairobi',
    value: '(GMT+03:00) Nairobi',
    offsetName: 'GMT+03:00',
    useDaylightTime: false,
    offset: 180,
  },
  {
    text: '(GMT+03:00) Tbilisi',
    value: '(GMT+03:00) Tbilisi',
    offsetName: 'GMT+03:00',
    useDaylightTime: false,
    offset: 180,
  },
  {
    text: '(GMT+03:30) Tehran',
    value: '(GMT+03:30) Tehran',
    offsetName: 'GMT+03:30',
    useDaylightTime: true,
    offset: 210,
  },
  {
    text: '(GMT+04:00) Abu Dhabi, Muscat',
    value: '(GMT+04:00) Abu Dhabi, Muscat',
    offsetName: 'GMT+04:00',
    useDaylightTime: false,
    offset: 240,
  },
  {
    text: '(GMT+04:00) Baku',
    value: '(GMT+04:00) Baku',
    offsetName: 'GMT+04:00',
    useDaylightTime: true,
    offset: 240,
  },
  {
    text: '(GMT+04:00) Yerevan',
    value: '(GMT+04:00) Yerevan',
    offsetName: 'GMT+04:00',
    useDaylightTime: true,
    offset: 240,
  },
  {
    text: '(GMT+04:30) Kabul',
    value: '(GMT+04:30) Kabul',
    offsetName: 'GMT+04:30',
    useDaylightTime: false,
    offset: 270,
  },
  {
    text: '(GMT+05:00) Yekaterinburg',
    value: '(GMT+05:00) Yekaterinburg',
    offsetName: 'GMT+05:00',
    useDaylightTime: true,
    offset: 300,
  },
  {
    text: '(GMT+05:00) Islamabad, Karachi, Tashkent',
    value: '(GMT+05:00) Islamabad, Karachi, Tashkent',
    offsetName: 'GMT+05:00',
    useDaylightTime: false,
    offset: 300,
  },
  {
    text: '(GMT+05:30) Sri Jayawardenapura',
    value: '(GMT+05:30) Sri Jayawardenapura',
    offsetName: 'GMT+05:30',
    useDaylightTime: false,
    offset: 330,
  },
  {
    text: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    value: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    offsetName: 'GMT+05:30',
    useDaylightTime: false,
    offset: 330,
  },
  {
    text: '(GMT+05:45) Kathmandu',
    value: '(GMT+05:45) Kathmandu',
    offsetName: 'GMT+05:45',
    useDaylightTime: false,
    offset: 345,
  },
  {
    text: '(GMT+06:00) Almaty, Novosibirsk',
    value: '(GMT+06:00) Almaty, Novosibirsk',
    offsetName: 'GMT+06:00',
    useDaylightTime: true,
    offset: 360,
  },
  {
    text: '(GMT+06:00) Astana, Dhaka',
    value: '(GMT+06:00) Astana, Dhaka',
    offsetName: 'GMT+06:00',
    useDaylightTime: false,
    offset: 360,
  },
  {
    text: '(GMT+06:30) Yangon (Rangoon)',
    value: '(GMT+06:30) Yangon (Rangoon)',
    offsetName: 'GMT+06:30',
    useDaylightTime: false,
    offset: 390,
  },
  {
    text: '(GMT+07:00) Bangkok, Hanoi, Jakarta',
    value: '(GMT+07:00) Bangkok, Hanoi, Jakarta',
    offsetName: 'GMT+07:00',
    useDaylightTime: false,
    offset: 420,
  },
  {
    text: '(GMT+07:00) Krasnoyarsk',
    value: '(GMT+07:00) Krasnoyarsk',
    offsetName: 'GMT+07:00',
    useDaylightTime: true,
    offset: 420,
  },
  {
    text: '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    value: '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    offsetName: 'GMT+08:00',
    useDaylightTime: false,
    offset: 480,
  },
  {
    text: '(GMT+08:00) Kuala Lumpur, Singapore',
    value: '(GMT+08:00) Kuala Lumpur, Singapore',
    offsetName: 'GMT+08:00',
    useDaylightTime: false,
    offset: 480,
  },
  {
    text: '(GMT+08:00) Irkutsk, Ulaan Bataar',
    value: '(GMT+08:00) Irkutsk, Ulaan Bataar',
    offsetName: 'GMT+08:00',
    useDaylightTime: false,
    offset: 480,
  },
  {
    text: '(GMT+08:00) Perth',
    value: '(GMT+08:00) Perth',
    offsetName: 'GMT+08:00',
    useDaylightTime: false,
    offset: 480,
  },
  {
    text: '(GMT+08:00) Taipei',
    value: '(GMT+08:00) Taipei',
    offsetName: 'GMT+08:00',
    useDaylightTime: false,
    offset: 480,
  },
  {
    text: '(GMT+09:00) Osaka, Sapporo, Tokyo',
    value: '(GMT+09:00) Osaka, Sapporo, Tokyo',
    offsetName: 'GMT+09:00',
    useDaylightTime: false,
    offset: 540,
  },
  {
    text: '(GMT+09:00) Seoul',
    value: '(GMT+09:00) Seoul',
    offsetName: 'GMT+09:00',
    useDaylightTime: false,
    offset: 540,
  },
  {
    text: '(GMT+09:00) Yakutsk',
    value: '(GMT+09:00) Yakutsk',
    offsetName: 'GMT+09:00',
    useDaylightTime: true,
    offset: 540,
  },
  {
    text: '(GMT+09:30) Adelaide',
    value: '(GMT+09:30) Adelaide',
    offsetName: 'GMT+09:30',
    useDaylightTime: false,
    offset: 570,
  },
  {
    text: '(GMT+09:30) Darwin',
    value: '(GMT+09:30) Darwin',
    offsetName: 'GMT+09:30',
    useDaylightTime: false,
    offset: 570,
  },
  {
    text: '(GMT+10:00) Brisbane',
    value: '(GMT+10:00) Brisbane',
    offsetName: 'GMT+10:00',
    useDaylightTime: false,
    offset: 600,
  },
  {
    text: '(GMT+10:00) Canberra, Melbourne, Sydney',
    value: '(GMT+10:00) Canberra, Melbourne, Sydney',
    offsetName: 'GMT+10:00',
    useDaylightTime: true,
    offset: 600,
  },
  {
    text: '(GMT+10:00) Hobart',
    value: '(GMT+10:00) Hobart',
    offsetName: 'GMT+10:00',
    useDaylightTime: true,
    offset: 600,
  },
  {
    text: '(GMT+10:00) Guam, Port Moresby',
    value: '(GMT+10:00) Guam, Port Moresby',
    offsetName: 'GMT+10:00',
    useDaylightTime: false,
    offset: 600,
  },
  {
    text: '(GMT+10:00) Vladivostok',
    value: '(GMT+10:00) Vladivostok',
    offsetName: 'GMT+10:00',
    useDaylightTime: true,
    offset: 600,
  },
  {
    text: '(GMT+11:00) Magadan, Solomon Is., New Caledonia',
    value: '(GMT+11:00) Magadan, Solomon Is., New Caledonia',
    offsetName: 'GMT+11:00',
    useDaylightTime: true,
    offset: 660,
  },
  {
    text: '(GMT+12:00) Auckland, Wellington',
    value: '(GMT+12:00) Auckland, Wellington',
    offsetName: 'GMT+12:00',
    useDaylightTime: true,
    offset: 720,
  },
  {
    text: '(GMT+12:00) Fiji, Kamchatka, Marshall Is.',
    value: '(GMT+12:00) Fiji, Kamchatka, Marshall Is.',
    offsetName: 'GMT+12:00',
    useDaylightTime: false,
    offset: 720,
  },
  {
    text: "(GMT+13:00) Nuku'alofa",
    value: "(GMT+13:00) Nuku'alofa",
    offsetName: 'GMT+13:00',
    useDaylightTime: false,
    offset: 780,
  },
];

module.exports = {
  Timezones,
};
