export const mutations = {
    LOADING: 'LOADING',
    SET_USER: 'SET_USER',
    SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    SET_VIEW_TYPES: 'SET_VIEW_TYPES',
    SET_CURRENT_DEVICE: 'SET_CURRENT_DEVICE',
    SET_DEVICES: 'SET_DEVICES',
    SET_DEVICES_FETCHED: 'SET_DEVICES_FETCHED',
    SET_SELECTED_DEVICE_TYPE: 'SET_SELECTED_DEVICE_TYPE',
    SET_ALL_DEVICES: 'SET_ALL_DEVICES',
    SET_SEARCH_NAME: 'SET_SEARCH_NAME',
    SET_USER_SUBSCRIPTIONS: 'SET_USER_SUBSCRIPTIONS',
};

export const actions = {
    LOAD_DEVICES: 'LOAD_DEVICES',
    UPDATE_DEVICE: 'UPDATE_DEVICE',
};
